# Generated by Django 3.2.5 on 2021-07-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Guest', max_length=75)),
                ('last_name', models.CharField(default='Donor', max_length=75)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
            ],
        ),
    ]
