# Generated by Django 3.2.5 on 2021-07-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='first_name',
            field=models.CharField(default='Anonymous', max_length=75),
        ),
    ]
