# Generated by Django 3.2.5 on 2021-08-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0003_alter_donor_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={'verbose_name': 'Donor', 'verbose_name_plural': 'Donors'},
        ),
    ]
