# Generated by Django 3.2.5 on 2021-07-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Package', '0004_alter_package_recurring_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=4),
        ),
    ]
