# Generated by Django 3.2.5 on 2021-07-08 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Package', '0005_package_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(1, message='Amount should be at least 1')]),
        ),
        migrations.AlterField(
            model_name='package',
            name='currency',
            field=models.CharField(blank=True, default='USD', help_text="List of supported currencies can be found <a href='https://developer.paypal.com/docs/api/reference/currency-codes/'  target='_blank'>here.</a>", max_length=4),
        ),
    ]
