# Generated by Django 3.2.5 on 2021-07-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Package', '0007_package_gateway_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='gateway_keys',
            field=models.JSONField(default=dict),
        ),
    ]
