# Generated by Django 3.2.5 on 2021-07-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Package', '0008_alter_package_gateway_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='gateway_keys',
        ),
    ]
