# Generated by Django 3.2.5 on 2021-07-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Package', '0009_remove_package_gateway_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Whether to show this package or not', verbose_name='Mark as Hidden'),
        ),
    ]
