# Generated by Django 3.2.5 on 2021-08-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Package', '0011_alter_package_recurring_interval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
    ]
