# Generated by Django 3.2.5 on 2021-07-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(default=None, max_length=150)),
                ('client_key', models.CharField(default=False, max_length=150)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('razorpay', 'RazorPay')], default='stripe', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SMTPService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('host', models.CharField(default=None, max_length=150)),
                ('port', models.IntegerField(default=None)),
                ('username', models.CharField(default=None, max_length=50)),
                ('password', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default=None, max_length=30)),
                ('body', models.TextField(default=None, max_length=1024)),
            ],
        ),
    ]
