# Generated by Django 3.2.5 on 2021-07-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMTPService',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='client_key',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
