# Generated by Django 3.2.5 on 2021-07-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0003_paymentmethod_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='environment',
            field=models.CharField(blank=True, choices=[('dev', 'Development'), ('prod', 'Production')], default='dev', help_text='Required for PayPal', max_length=4),
        ),
    ]
