# Generated by Django 3.2.5 on 2021-07-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0005_paymentmethod_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='wh_id',
            field=models.CharField(blank=True, default=None, help_text='Required for RazorPay', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, help_text='Use this payment method'),
        ),
    ]
