# Generated by Django 3.2.5 on 2021-07-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0006_auto_20210708_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='wh_id',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, help_text='Use this payment method', verbose_name='Active Method'),
        ),
    ]
