# Generated by Django 3.2.5 on 2021-07-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0007_auto_20210708_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, help_text='Custom message', verbose_name='Mark as Active'),
        ),
    ]
