# Generated by Django 3.2.5 on 2021-07-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0008_alter_paymentmethod_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='wh_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
