# Generated by Django 3.2.5 on 2021-07-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0009_paymentmethod_wh_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='client_key',
            field=models.CharField(default=None, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='secret_key',
            field=models.CharField(default=None, max_length=150, unique=True),
        ),
    ]
