# Generated by Django 3.2.5 on 2021-08-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0011_alter_paymentmethod_wh_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique of the name', max_length=50, verbose_name='Field Name')),
                ('placeholder', models.CharField(blank=True, help_text='Placeholder text for the input field', max_length=75, null=True, verbose_name='Placeholder Text')),
                ('attributes', models.JSONField(verbose_name='Attributes')),
                ('type', models.CharField(choices=[('url', 'URL'), ('date', 'Date'), ('datetime-local', 'Local DateTime'), ('time', 'Time'), ('tel', 'Telephone'), ('text', 'Text'), ('email', 'Email'), ('number', 'Number')], default='text', help_text='Type of input field to use. Use this as HTML validation', max_length=15, verbose_name='Field Type')),
            ],
        ),
    ]
