# Generated by Django 3.2.5 on 2021-08-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0012_customfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='help_text',
            field=models.TextField(default='', help_text='Enter help description for the field. This should be shown on the checkout page', max_length=256, verbose_name='Help Text'),
        ),
    ]
