# Generated by Django 3.2.5 on 2021-08-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0013_customfield_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='attributes',
            field=models.JSONField(blank=True, help_text='Input tag extra attributes as JSON', null=True, verbose_name='Attributes (Optional)'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='help_text',
            field=models.TextField(blank=True, default='', help_text='Enter help description for the field. This should be shown on the checkout page', max_length=256, verbose_name='Help Text (Optional)'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='placeholder',
            field=models.CharField(blank=True, help_text='Placeholder text for the input field', max_length=75, null=True, verbose_name='Placeholder Text (Optional)'),
        ),
    ]
