# Generated by Django 3.2.5 on 2021-08-18 19:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0014_auto_20210812_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPSever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default=None, help_text='Enter IP/hostname to connect', max_length=256, verbose_name='Hostname')),
                ('username', models.CharField(blank=True, help_text='Enter username for authentication', max_length=128, null=True, verbose_name='Username (Optional)')),
                ('password', models.CharField(blank=True, help_text='Enter username for authentication', max_length=128, null=True, verbose_name='Password (Optional)')),
                ('port', models.IntegerField(choices=[(25, '25 - Insecure'), (465, '465 - SSL Secure'), (587, '587 - TLS Secure')], default=25, help_text='Enter port number', verbose_name='Port number')),
                ('template', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
