# Generated by Django 3.2.5 on 2021-08-18 19:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0015_smtpsever'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpsever',
            name='subject',
            field=models.CharField(default=None, help_text='Enter email subject', max_length=128, verbose_name='Email Subject'),
        ),
        migrations.AlterField(
            model_name='smtpsever',
            name='template',
            field=ckeditor.fields.RichTextField(default=None, help_text='Enter email body here', verbose_name='Email Body'),
        ),
    ]
