# Generated by Django 3.2.5 on 2021-08-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0017_auto_20210818_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpsever',
            name='event',
            field=models.CharField(choices=[('success', 'Payment Succeeded'), ('fail', 'Payment Failed')], default='success', help_text='Select when you want to send the email to donors', max_length=7, verbose_name='Trigger event'),
        ),
    ]
