# Generated by Django 3.2.5 on 2021-08-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0018_smtpsever_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='secret_key',
            field=models.CharField(default=None, help_text='Once it is saved, you can not retrieve it later due to security reasons', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='smtpsever',
            name='password',
            field=models.CharField(default=None, help_text='Enter username for authentication. Once it is saved, you can not retrieve it later due to security reasons', max_length=128, verbose_name='Password'),
        ),
    ]
