# Generated by Django 3.2.5 on 2021-08-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0019_auto_20210818_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='secret_key',
            field=models.CharField(default=None, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='smtpsever',
            name='password',
            field=models.CharField(default=None, help_text='Enter password for authenticating SMTP server', max_length=128, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='smtpsever',
            name='username',
            field=models.CharField(default=None, help_text='Enter username for authenticating SMTP server', max_length=128, verbose_name='Username'),
        ),
    ]
