# Generated by Django 3.2.5 on 2021-08-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0021_auto_20210818_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpsever',
            name='from_email',
            field=models.CharField(default='no_reply@donorgrid.io', help_text='Enter the email address from which you want to send the email', max_length=75, verbose_name='From Email'),
        ),
        migrations.AddField(
            model_name='smtpsever',
            name='from_name',
            field=models.CharField(default='DonorGrid', help_text='Enter the name from which you want to send the email', max_length=50, verbose_name='From Name'),
        ),
    ]
