# Generated by Django 3.2.5 on 2021-08-18 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0022_auto_20210818_1958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SMTPSever',
            new_name='SMTPServer',
        ),
    ]
