# Generated by Django 3.2.5 on 2021-08-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0024_auto_20210821_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a human-friendly webhook name', max_length=50, verbose_name='Webhook Entry Name')),
                ('webhook_url', models.URLField(verbose_name='Webhook URL')),
                ('event', models.CharField(choices=[('on_payment_success', 'On Payment Success'), ('on_payment_fail', 'On Payment Fail'), ('on_donor_create', 'On Donor Create')], default='on_donor_create', help_text='Select when you want to trigger this webhook', max_length=20, verbose_name='Trigger Event')),
                ('service', models.CharField(choices=[('zapier', 'Zapier'), ('paybbly_connect', 'Pabbly Connect')], default='zapier', help_text='Select the automation service for integration', max_length=20, verbose_name='Automation Service')),
            ],
            options={
                'verbose_name': 'Automation Service',
                'verbose_name_plural': 'Automation Services',
            },
        ),
    ]
