# Generated by Django 3.2.5 on 2021-08-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0025_automation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='name',
            field=models.CharField(default=None, help_text='Enter a human-friendly webhook name', max_length=50, verbose_name='Webhook Entry Name'),
        ),
    ]
