# Generated by Django 3.2.5 on 2021-08-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0026_alter_automation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='webhook_url',
            field=models.URLField(default=None, verbose_name='Webhook URL'),
        ),
    ]
