# Generated by Django 3.2.5 on 2021-07-02 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Package', '0002_auto_20210702_1946'),
        ('Donor', '0002_alter_donor_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('currency', models.CharField(default='USD', max_length=4)),
                ('donor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Donor.donor')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Package.package')),
            ],
        ),
    ]
