# Generated by Django 3.2.5 on 2021-07-02 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Package', '0004_alter_package_recurring_interval'),
        ('Donation', '0002_remove_donation_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Package.package'),
        ),
    ]
