# Generated by Django 3.2.5 on 2021-07-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donation', '0003_alter_donation_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=3),
        ),
    ]
