# Generated by Django 3.2.5 on 2021-07-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donation', '0004_donation_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('razorpay', 'RazorPay')], default='stripe', max_length=15),
        ),
        migrations.AddField(
            model_name='donation',
            name='txn_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
