# Generated by Django 3.2.5 on 2021-07-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donation', '0005_auto_20210708_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
