# Generated by Django 3.2.8 on 2021-11-12 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CrowdFunding', '0001_initial'),
        ('Donation', '0009_alter_donation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='funding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CrowdFunding.funding'),
        ),
    ]
