version: '3.3'

services:
  nginx:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - static:/var/www/html
      - uploads:/var/www/html/uploads
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.ssl.sh:/docker-entrypoint.d/40-enable-ssl.sh
    ports:
      - 80:80
      - 443:443
  app:
    depends_on:
      - db
    build: .
    volumes:
      - static:/app/static
      - uploads:/app/uploads
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: donorgrid
      POSTGRES_DB: donorgrid
      POSTGRES_USER: donorgrid

volumes:
  static:
    driver: local
  uploads:
    driver: local
