version: '3.3'

services:
  app:
    depends_on:
      - db
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - /var/www/html/donorgrid/static:/app/static
      - /var/www/html/donorgrid/uploads:/app/uploads
      - /var/log/donorgrid:/var/log/donorgrid
    restart: on-failure
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: donorgrid
      POSTGRES_DB: donorgrid
      POSTGRES_USER: donorgrid
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: