version: '3.3'

services:
  app:
    depends_on:
      - db
    build: .
    volumes:
      - static:/app/static
      - uploads:/app/uploads
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: donorgrid
      POSTGRES_DB: donorgrid
      POSTGRES_USER: donorgrid

volumes:
  static:
    driver: local
  uploads:
    driver: local
