# Generated by Django 3.2.8 on 2021-11-12 04:45

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='Enter the name for funding campaign', max_length=128, verbose_name='Name')),
                ('description', ckeditor.fields.RichTextField(default=None, help_text='Let donors know more about the campaign', max_length=256, verbose_name='Description')),
                ('target', models.FloatField(default=1.0, help_text='Enter the target amount of the funding. If not deactivated, it will automatically deactive once the donation read its limit', validators=[django.core.validators.MinValueValidator(1.0, message='Target should be at least 1.0')])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Current status of the funding. Only active fundings can request for donations from the users', max_length=25, verbose_name='Current Status')),
            ],
            options={
                'verbose_name': 'Funding',
                'verbose_name_plural': 'Fundings',
            },
        ),
    ]
