# Generated by Django 3.2.8 on 2021-11-12 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrowdFunding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='target',
            field=models.FloatField(default=1.0, help_text='Enter the target amount of the funding', validators=[django.core.validators.MinValueValidator(1.0, message='Target should be at least 1.0')]),
        ),
    ]
